apiVersion: v1
kind: ConfigMap
metadata:
  name: xss-config
data:
  index.html: |
    ... (seu conteúdo HTML) ...
  nginx.conf: |
    worker_processes 1;
    pid /tmp/nginx.pid;
    events { worker_connections 1024; }
    http {
        server {
            listen 8080; # Porta não privilegiada
            server_name localhost;
            location / { root /usr/share/nginx/html; }
        }
    }
