[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "cyberlab_plugin_podman"

[project]
name = "podman"
version = "0.1.0"
description = "Podman"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "cyberlab",
]

[tool.uv.sources]
cyberlab = { path = "..", editable = true }

[project.urls]
Homepage = "https://github.com/guiisme84/CyberLab"
Repository = "https://github.com/guiisme84/CyberLab"

[project.entry-points."cyberlab.plugins"]
"podman" = "cyberlab_plugin_podman.plugin:Podman"
